language: python
dist: focal
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - pip install pipupgrade
  - pipupgrade --verbose --latest --yes
  - pip install poetry
install:
  - poetry install
  - poetry run safety check
  - poetry run bandit -r sutime/*.py
  - poetry run dodgy
  - poetry run pyre --noninteractive check
  - mvn dependency:copy-dependencies -DoutputDirectory=./sutime/jars -P spanish
script:
  - python -c 'import platform; print(platform.python_version().startswith("3.9"))' | grep True > /dev/null && echo 'Skipping flake8 on Python 3.9' || poetry run flake8 sutime
  - poetry run pytest
  - poetry build
deploy:
  - provider: releases
    api_key:
      secure: "Pjp8cawO021uxziqDvbil8UoRNakQlIc33hVnqGidfBM0Refeok0uA8xM8rvdn5zgZGLb48UyI4kYHRi8sggHHCBdCVLP2G3O8DI7gaV7wxRtWsadulRJyZpbnoaT+htGqtcKE5911VXC2bRCKTRRpftnCWGtTwbuH7E3DecvDWJTX+O2vGo1U30EZMVfmkf9robN66G+U5P5C+7x+uJpUX4UkbTINbRAZra82Jl1PPiMtPCi60Tx3s2TbzSkQl2tUj7D0XU6VeTtCDL1d/PUGV68C2pVnjJ17ppMspx0Qlof4+m/AznQ8MgEJ82JPVLMNOn8aZBZ5O1GBUdCGQRMBWVQYGcpocX0xv6PEhUxgmtmpzPzB6gf+ISyyLuMOg8pSQphM7+4dY6/xNY9/BhQHmpG6QRKTQHtssKoeo5i5AaB4WU7Vg8EbdjHhOKY8ovcrmYkaCxU1J2u6Kl3R0kszHOXm548+wHcUV8Df8MzUS3hqoH3+lODLFVzZmQz40GCYKLm0u0furO39r7HE2UYFB5h/rXbrYkdXhbXKHW3LfVB1mfudxp5JJXLQNV/X69amVAuubjpRkU6OgnILmbfaLRC39nuFirkvm9J5xGO9v/UYj6nUGncRNLzX7i7UyCAn5hhvI0HDcCji6XbwA6J+WPXzMhnzbxhAv5e4NkRmo="
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
  - provider: pypi
    username: "__token__"
    password:
      secure: "B15CvW9feRFZJyO4vJY+Z98Fo+dT2WyPeMkkDwq0H6Vy3b5TVI/goBcHcsBprvWUjvbLM47sdOMI025dAsFhquSW3+nUEON2OIiLbjdaldesvaQfZbIdMg1FEqCH4xVLb6QYY6SmGovcyB0t7ls9legQJIrbuRJDiGCy7mO/gXIxuK1qOszjvJmQMYjqQiahu4q0Uo+seC4v/SJAo0MDvPWZBFD4nmlXq6RN/UHF9g7mYTjxXPTrAtUfovYqJR3jHfJ1tzfH3Znc/buhhei1Aaevz0dtEyNQk/pNgdqvGpIL1HaUrgpNUZ6GIzRslpMVycN2EIGGt6Uw3c5o7qlltv8fgPA1tLG4a3PrCCMvbKmzZKgHTqIOiFF5Mjuv3ruRlA0kNw+zIzn2MA/7gu0e8TSL+g+2Ub/uwZknyVhCNsZ507w+KMg2/WMQamUpSEIjDkhMlv/A11fUCbQnRTPlYST1oz1Jcg1o5Ot57fywMKj/ggFVrgMW8GrIPDmH6SNLeJYJNAA+hKRb0GAWMOX3gCSMWAUBzBtoyq5V3q0nxdGeMABTCHLtmp5t369XmTKwqlnul+G28xrR0COswkDQ3M2HEsps44eSvRqdZL+fXvpRo5+kqf63FpBGzyRYhqKn3MOXl4wra/fJngp8fM4z+VqYc9PpfXiSAjpYjzDBqJc="
    distributions: "sdist wheel"
    skip_existing: true
    skip_cleanup: true
    on:
      tags: true
