language: python
dist: focal
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - pip install poetry
install:
  - poetry install
  - mvn dependency:copy-dependencies -DoutputDirectory=./sutime/jars -P spanish
script:
  - poetry run pytest
