# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # This was the easiest way to get Python, the JRE and Maven in one image
      - image: openkbs/jre-mvn-py3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "pom.xml" }}

      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip setuptools bandit xenon pylint
            python3 setup.py install
            mvn dependency:copy-dependencies -DoutputDirectory=./jars -P spanish

      - save_cache:
          paths:
            - ./venv
            - ./jars
          key: v1-dependencies-{{ checksum "setup.py" }}-{{ checksum "pom.xml" }}

      - run:
          name: Create test reports folder
          command: mkdir test-reports

      - run:
          name: Run linter
          command: pylint sutime 2>&1 | tee ./test-reports/linter.txt

      - run:
          name: Run complexity check
          command: xenon --max-absolute B --max-modules B --max-average A sutime 2>&1 | tee ./test-reports/complexity.txt

      - run:
          name: Run security linter
          command: bandit -r ./sutime/sutime.py 2>&1 | tee ./test-reports/bandit.txt

      - run:
          name: Run tests
          command: ./test.sh

      - store_artifacts:
          path: test-reports
          destination: test-reports
